### ISSUE TITLE
unjustified show in smartie detail on windows

### ISSUE THREAD

**Issue by jackeichen** [TkTech/smartie#18]
Here is the format(line with ℃):

![1720678275234](https://github.com/TkTech/smartie/assets/20065172/d97554e2-146e-477b-a263-dc2c76ef948e)

And my python module version:
```
C:\Users\>pip list
Package        Version
-------------- -------
click          8.1.7
colorama       0.4.6
Cython         3.0.10
markdown-it-py 3.0.0
mdurl          0.1.2
pip            24.0
psutil         5.9.8
PYDISKCMD      0.3.2
Pygments       2.18.0
rich           13.7.1
smartie        4.0.3

```

**Comment by TkTech** [comment]
This is caused by the terminal incorrectly calculating the width of the degrees character. Hm. I think I'll just remove it, it's clear from the C or F what was intended.
